### ISSUE TITLE
upgrade CRD to `apiextensions.k8s.io/v1`

### ISSUE THREAD

**Issue by akanso** [ray-project/ray-contrib#13]
upgrade CRD from `apiextensions.k8s.io/v1beta1` to `apiextensions.k8s.io/v1`

to avoid:

`Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition`

**Comment by Jeffwan** [comment]
I bump up controller-get from 0.2.2 to 0.5.0 and regenerate CRD in this PR https://github.com/ray-project/ray-contrib/pull/22

**Comment by Jeffwan** [comment]
latest controller-gen gives us v1 CRD version. It's been used in master already. We can close the issue
