### ISSUE TITLE
Use squash merge for pull requests or introduce bot to manage merge

### ISSUE THREAD

**Issue by Jeffwan** [ray-project/ray-contrib#6]
Seem this repo is growing and repo doesn't have a common way to manage pull requests.

I would suggest to use "squash merge" which makes commit history clean and easy to mange. 

In addition, it would be better to introduce bot to manage PR or issues. 

/cc @akanso @Qstar

**Comment by Jeffwan** [comment]
If you don't mind, I will change default merge way to `Squash and merge`

**Comment by Qstar** [comment]
> If you don't mind, I will change default merge way to `Squash and merge`

LGTM, thanks for the advice.

**Comment by akanso** [comment]
good point! I agree...

**Comment by Jeffwan** [comment]
![image](https://user-images.githubusercontent.com/4739316/131556216-db3e6afe-abc2-4606-9221-ac6c4f0b85d5.png)

Great! Seems we got everyone's agreement. I cancel  merge and rebase merge, only `rebase and merge` is provided. This requires us write clear commit logs in the PR.
